#!/usr/bin/env bash
# Assemble the deployable site into dist/ — no build tooling, just a clean copy
# of exactly the files the browser needs (keeps private/backup files out),
# plus one generated file: sw-manifest.js, the service worker's precache list,
# versioned by a content hash of the shell so every deploy is an atomic update.
#
# Kill switch: `KILL=1 ./build.sh` ships a manifest that makes the service
# worker unregister itself and clear its caches on every user's next visit.
set -e
cd "$(dirname "$0")"
rm -rf dist
mkdir -p dist
cp index.html landing.html manifest.webmanifest favicon.svg robots.txt CHANGELOG.md vercel.json sw.js dist/
cp -R css js fonts vendor dist/

# ── Service-worker precache manifest ─────────────────────────────────────────
# SW_ASSETS: the app shell (html/css/js incl. vendored libs) — precached as one
#            atomic version, old version dropped on activation.
# SW_FONTS:  woff2 files (UI fonts + KaTeX) — precached into a stable cache
#            that survives version switches, so fonts never re-download.
(
  cd dist
  ASSETS=$(find css js vendor -type f \( -name '*.css' -o -name '*.js' \) | sort)
  FONT_FILES=$(find fonts vendor/katex/fonts -type f -name '*.woff2' | sort)
  HASH=$(cat index.html landing.html manifest.webmanifest $ASSETS | shasum | cut -c1-12)
  {
    echo "// Generated by build.sh — do not edit or commit; regenerated every build."
    echo "const SW_VERSION='$HASH';"
    echo "const SW_KILL=$([ -n "$KILL" ] && echo true || echo false);"
    echo "const SW_ASSETS=["
    echo "'/index.html','/landing.html','/favicon.svg','/manifest.webmanifest',"
    for f in $ASSETS; do echo "'/$f',"; done
    echo "];"
    echo "const SW_FONTS=["
    for f in $FONT_FILES; do echo "'/$f',"; done
    echo "];"
  } > sw-manifest.js
  echo "sw-manifest.js: version $HASH$([ -n "$KILL" ] && echo ' (KILL SWITCH ON)')"
)
echo "dist/ ready ($(find dist -type f | wc -l | tr -d ' ') files) — drag the dist/ folder onto your host."
