/* Fetch Google Fonts css2, download latin/latin-ext woff2 files into fonts/,
   and emit css/00-fonts.css with local URLs. Run from the repo root. */
const fs = require('fs'), path = require('path'), https = require('https');

const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';
const CSS_URLS = [
  'https://fonts.googleapis.com/css2?family=Cormorant:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400&family=Newsreader:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400&family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500&family=DM+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400&family=Inter:wght@300;400;500;600;700&family=DM+Mono:ital,wght@0,300;0,400;0,500;1,300;1,400&display=swap',
  'https://fonts.googleapis.com/css2?family=Pixelify+Sans:wght@400;500;600;700&family=VT323&display=swap',
];
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

function get(url, binary) {
  return new Promise((res, rej) => {
    https.get(url, { headers: { 'User-Agent': UA } }, r => {
      if (r.statusCode >= 300 && r.headers.location) return res(get(r.headers.location, binary));
      if (r.statusCode !== 200) return rej(new Error(r.statusCode + ' ' + url));
      const chunks = [];
      r.on('data', c => chunks.push(c));
      r.on('end', () => res(binary ? Buffer.concat(chunks) : Buffer.concat(chunks).toString('utf8')));
    }).on('error', rej);
  });
}

(async () => {
  const root = process.cwd();
  const fontsDir = path.join(root, 'fonts');
  fs.mkdirSync(fontsDir, { recursive: true });

  const urlToFile = new Map();   // remote URL -> local filename (dedup: variable fonts share files)
  const outBlocks = [];
  let total = 0;

  for (const cssUrl of CSS_URLS) {
    const css = await get(cssUrl, false);
    // css2 output: "/* <subset> */\n@font-face { ... }" repeated
    const re = /\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
    let m;
    while ((m = re.exec(css))) {
      const subset = m[1];
      let block = m[2];
      if (!KEEP_SUBSETS.has(subset)) continue;
      const fam = (block.match(/font-family:\s*'([^']+)'/) || [])[1] || 'font';
      const style = (block.match(/font-style:\s*(\w+)/) || [])[1] || 'normal';
      const weight = ((block.match(/font-weight:\s*([\d ]+)/) || [])[1] || '400').trim().replace(/\s+/g, '-');
      const src = (block.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
      if (!src) continue;
      let file = urlToFile.get(src);
      if (!file) {
        const slug = fam.toLowerCase().replace(/\s+/g, '');
        file = `${slug}-${style === 'italic' ? 'i' : 'n'}${weight}-${subset}.woff2`;
        // collision guard (same face, same subset, different URL shouldn't happen — but be safe)
        let n = 2, base = file;
        while ([...urlToFile.values()].includes(file)) file = base.replace(/\.woff2$/, `-${n++}.woff2`);
        urlToFile.set(src, file);
        const buf = await get(src, true);
        fs.writeFileSync(path.join(fontsDir, file), buf);
        total += buf.length;
        console.log('  ' + file + '  ' + (buf.length / 1024).toFixed(0) + 'K');
      }
      block = block.replace(/url\(https:[^)]+\.woff2\)/, `url(../fonts/${file})`);
      outBlocks.push(`/* ${fam} ${style} ${weight} ${subset} */\n` + block);
    }
  }

  const header = `/* ═══════════════════════════════════════════════
   00-FONTS — self-hosted Google Fonts (latin + latin-ext subsets, woff2)
   Generated by scripts/vendor-fonts.js — do not edit by hand; re-run the
   script to refresh. Other scripts fall back to system fonts.
═══════════════════════════════════════════════ */\n\n`;
  fs.writeFileSync(path.join(root, 'css', '00-fonts.css'), header + outBlocks.join('\n') + '\n');
  console.log(`\n${urlToFile.size} files, ${(total / 1024 / 1024).toFixed(2)} MB → fonts/`);
  console.log(`${outBlocks.length} @font-face rules → css/00-fonts.css`);
})().catch(e => { console.error(e); process.exit(1); });
